### ISSUE TITLE
is it a problem if the config.json is already in here?

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/app-subj2reference#1]
This repo already contains a config.json.  Does this just get overwritten, or might it cause problems?

https://github.com/brainlife/app-subj2reference/blob/master/config.json

**Comment by faskowit** [comment]
id say to just delete it. no problemo.

**Comment by DanNBullock** [comment]
Partially the concern is "has this been impacting previous runs of the
app?"  My guess is no, because I don't see how the dockerized version of
this could access Soichi's directory on IU's system.

**Comment by faskowit** [comment]
I think you should indeed get rid of the json here.  At best, it's just gonna get overwritten by brainlife when running correctly.  At worst, it just causes confusion

**Comment by francopestilli** [comment]
@DanNBullock  good catch. We use the config.json.example to provide an example for others to understand how to use the code locally. I renamed the file and committed it.
